[package]
name = "ii-bitcoin"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
bitcoin_hashes = "0.3.2"
lazy_static = "1.3"
packed_struct_codegen = "0.3"
packed_struct="0.3"
uint = "0.5.0"
