[package]
name = "ii-wire"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
# FIXME: update comment
# Note: Tokio is currently pinned to 0.1.19 and rustc is pinned to nightly-2019-05-10
# using the toolchain file, becase async-await-preview is broken in Tokio 0.1.20
# cf. https://github.com/tokio-rs/tokio/issues/1094
# Also, this dependency spec is used by dependant crates:
# This is the central place to specify Tokio dependency.
# FIXME: wait for https://github.com/tokio-rs/tokio/pull/1602
tokio = { git = "https://github.com/braiins/tokio.git", branch = "fix-incoming" }
tokio-io = { git = "https://github.com/braiins/tokio.git", branch = "fix-incoming" }
bytes = "0.4"
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }
failure = "0.1.5"
pin-project = "0.4.0-beta.1"   # The version that the above tokio uses
