[package]
name = "ii-wire"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.20", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
failure = "0.1.5"
pin-project = "0.4.5"
async-trait = "0.1.17"
thiserror = "1.0"

# failure caused a problem when they used private API from quote:
# https://users.rust-lang.org/t/failure-derive-compilation-error/39062
[patch.crates-io.failure]
path = "../../utils-rs/failure"
