[package]
name = "ii-wire"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
futures = "0.3.5"
tokio = { version = "0.2.20", features = ["full"] }
tokio-util = { version = "0.3.1", features = ["codec"] }
pin-project = "0.4.5"
thiserror = "1.0"
serde = { version = "1.0.114", optional = true }

[dev-dependencies]
serde_json = "1.0.56"
