[package]
name = "ii-wire"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
ii-async-compat = { path = "../../utils-rs/async-compat" }
failure = "0.1.5"
pin-project = "0.4.0-beta.1"   # The version that the currently used tokio uses
async-trait = "0.1.17"
