listen_address = "0.0.0.0:3336"
upstream_address = "eu.stratum.slushpool.com:3333"
insecure = false
certificate_file = "config/server-noise-static-public.cert"
secret_key_file = "config/server-noise-static-secret.key"
