[package]
name = "ii-stratum-proxy"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
bitcoin_hashes = "0.3.2"
uint = "0.5.0"
ctrlc = "3.1.0"
serde_json = "1.0.39"
async-trait = "0.1.17"
futures = { version = "0.3.1", features = ["compat"] }
bytes = "0.5"
tokio = { version = "0.2.10", features = ["full"] }
# tokio-util = { version = "0.2.0", features = ["codec"] }
ii-stratum = { path = "../protocols/stratum" }
ii-wire = { path = "../protocols/wire" }
ii-async-compat = { path = "../utils-rs/async-compat" }
ii-logging = { path = "../utils-rs/logging" }
structopt = "0.3"

[features]
v2json = ["ii-stratum/v2json"]

# failure caused a problem when they used private API from quote:
# https://users.rust-lang.org/t/failure-derive-compilation-error/39062
[patch.crates-io.failure]
path = "../utils-rs/failure"
