[package]
name = "stratumproxy"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.1.19", features = ["async-await-preview"] }
stratum = { path = "../protocols/stratum" }
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
failure = "0.1.5"

