[package]
name = "ii-stratum-proxy"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
clap = "2.33.0"
failure = "0.1.5"
bitcoin_hashes = "0.3.2"
uint = "0.5.0"
ctrlc = "3.1.0"
serde_json = "1.0.39"
async-trait = "0.1.17"
ii-stratum = { path = "../protocols/stratum" }
ii-wire = { path = "../protocols/wire" }
ii-async-compat = { path = "../utils-rs/async-compat" }
ii-logging = { path = "../utils-rs/logging" }

[features]
v2json = ["ii-stratum/v2json"]
