[package]
name = "stratum"
version = "0.1.0"
authors = ["Jan Čapek <jan@braiins.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
bytes = "0.4"
byteorder = "1.2.7"
hex = "0.3.2"
slog-envlogger = "2.1.0"
# Temporarily disabled, see v1 TODO
#serde_tuple = "0.2.2"
packed_struct = "0.3"
packed_struct_codegen = "0.3"
bitcoin_hashes = "0.3.2"
uint = "0.5.0"
wire = { path = "../wire" }
logging = { path = "../../utils-rs/logging" }
